GENERATED_IMG_PATH = "generated/resultado_imgs"
RESULT_FILE_NAME = GENERATED_IMG_PATH + "/resultado.txt"
classes = {
    '/0': '0',
    '/1': '1',
    '/2': '2',
    '/3': '3',
    '/4': '4',
    '/5': '5',
    '/6': '5',
    '/7': '7',
    '/8': '8',
    '/9': '9',
    '/may/A': 'A',
    '/may/B': 'B',
    '/may/C': 'C',
    '/may/D': 'D',
    '/may/E': 'E',
    '/may/F': 'F',
    '/may/G': 'G',
    '/may/H': 'H',
    '/may/I': 'I',
    '/may/J': 'J',
    '/may/K': 'K',
    '/may/L': 'L',
    '/may/M': 'M',
    '/may/N': 'N',
    '/may/O': 'O',
    '/may/P': 'P',
    '/may/Q': 'Q',
    '/may/R': 'R',
    '/may/S': 'S',
    '/may/T': 'T',
    '/may/U': 'U',
    '/may/V': 'V',
    '/may/W': 'W',
    '/may/X': 'X',
    '/may/Y': 'Y',
    '/may/Z': 'Z',
    '/min/a': 'a',
    '/min/b': 'b',
    '/min/c': 'c',
    '/min/d': 'd',
    '/min/e': 'e',
    '/min/f': 'f',
    '/min/g': 'g',
    '/min/h': 'h',
    '/min/i': 'i',
    '/min/j': 'j',
    '/min/k': 'k',
    '/min/l': 'l',
    '/min/m': 'm',
    '/min/n': 'n',
    '/min/o': 'o',
    '/min/p': 'p',
    '/min/q': 'q',
    '/min/r': 'r',
    '/min/s': 's',
    '/min/t': 't',
    '/min/u': 'u',
    '/min/v': 'v',
    '/min/w': 'w',
    '/min/x': 'x',
    '/min/y': 'y',
    '/min/z': 'z',
}

OCR_PATH = "generated/ocr"
